13-01-2025 at 00:42:58 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'AttributeError'>, Message:'Empm' object has no attribute 'abc'"}
13-01-2025 at 01:09:08 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'AttributeError'>, Message:'Envconst' object has no attribute 'SECRET_KEY'"}
13-01-2025 at 01:32:40 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'AttributeError'>, Message:'AuthMessage' object has no attribute 'SAVE_SUCCESS'"}
13-01-2025 at 01:33:52 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:2 validation errors for AuthOut\naccess_token\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing\ntoken_type\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
13-01-2025 at 01:35:51 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:2 validation errors for AuthOut\naccess_token\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing\ntoken_type\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
13-01-2025 at 01:37:50 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:2 validation errors for AuthOut\naccess_token\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing\ntoken_type\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
13-01-2025 at 01:40:14 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:2 validation errors for AuthOut\naccess_token\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing\ntoken_type\n  Field required [type=missing, input_value={'status_code': 200, 'sta...'mobile': '123456789'}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
